version: "2.4"

services:
  redis:
    image: "redis:alpine3.12"
    volumes:
      - "./config/redis/:/usr/local/etc/redis/:rw"

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  sandbox-worker:
    build: ./SandboxWorker
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      EXECUTABLES_VOLUME: "coderoom_executables"
      JOB_TIMEOUT: 6000
    command: sh -c './wait-for rabbitmq:5672 -- python worker.py'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - executables:/app/sandbox/code/
