version: '3.8'

services:
  redis:
    image: 'redis:alpine3.12'
    container_name: redis
    command: redis-server
    volumes:
      - './config/redis/:/usr/local/etc/redis/:rw'
    ports:
      - '6379:6379'
  rabbitmq:
    build: ./config/rabbitmq
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:            
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
  sandbox-worker:
    build: ./SandboxWorker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASS}
      EXECUTABLES_VOLUME: 'coderoom_executables'
    command: sh -c './wait-for rabbitmq:5672 -- python worker.py'
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock
      - executables:/app/sandbox/code/

volumes:
  executables:
    external:
      name: 'coderoom_executables'
