version: "2.4"

services:
  redis:
    extends:
      file: common-services.yml
      service: redis
    ports:
      - "6379:6379"
  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  sandbox-worker:
    extends:
      file: common-services.yml
      service: sandbox-worker

volumes:
executables:
  external:
    name: "coderoom_executables"
