version: "2.4"

services:
  redis:
    extends:
      file: common-services.yml
      service: redis
  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
  sandbox-worker:
    extends:
      file: common-services.yml
      service: sandbox-worker
    depends_on:
      - rabbitmq
  backend:
    build: ./Backend
    depends_on:
      - redis
      - rabbitmq
      - sandbox-worker
    ports:
      - "80:80"
      - "443:443"
    environment:
      RedisConnection: "redis:6379"
      EventBusConnection: "rabbitmq:5672"
      EventBusUsername: ${RABBITMQ_USER}
      EventBusPassword: ${RABBITMQ_PASS}
    command: sh -c './wait-for rabbitmq:5672 -- ./wait-for redis:6379 -- ./WebUI'

volumes:
  executables:
    external:
      name: "coderoom_executables"
