version: "2.4"

services:
  redis:
    extends:
      file: common-services.yml
      service: redis
    ports:
      - "6379:6379"

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  sandbox-worker:
    extends:
      file: common-services.yml
      service: sandbox-worker
    environment:
      ENVIRONMENT: "test"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      JOB_TIMEOUT: 25000

  web-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile.test
    environment:
      ASPNETCORE_ENVIRONMENT: "Test"
      JobTimeout: 25000
      Redis:Connection: "redis:6379"
      EventBus:Connection: "rabbitmq:5672"
      EventBus:Username: ${RABBITMQ_USER}
      EventBus:Password: ${RABBITMQ_PASS}
    command: dotnet test

volumes:
  executables:
    name: "coderoom_executables"
