FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /coderoom

RUN apt-get update && apt-get -y install --no-install-recommends openjdk-11-jdk-headless && apt-get clean && rm -r /var/lib/apt/lists/*

COPY . .