FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /coderoom

RUN mkdir -p /usr/share/man/man1 /usr/share/man/man2
RUN apt-get update && apt-get -y install --no-install-recommends openjdk-11-jdk-headless && apt-get clean && rm -r /var/lib/apt/lists/*

COPY . .